import pymysql
import config

def mysql_get_mydb():
    try:
        database = pymysql.connect(
            host=config.host,
            user=config.user,
            passwd=config.passwd,
            db=config.db
        )
    finally:
        return database

realms = ["aegwynn",
            "aerie_peak",
            "agamaggan",
            "aggramar",
            "akama",
            "alexstrasza",
            "alleria",
            "altar_of_storms",
            "alterac_mountains",
            "andorhal",
            "anetheron",
            "antonidas",
            "anub_arak",
            "anvilmar",
            "arathor",
            "archimonde",
            "area_52",
            "argent_dawn",
            "arthas",
            "arygos",
            "auchindoun",
            "azgalor",
            "azjol_nerub",
            "azshara",
            "azuremyst",
            "baelgun",
            "balnazzar",
            "black_dragonflight",
            "blackhand",
            "blackrock",
            "blackwater_raiders",
            "blackwing_lair",
            "blades_edge",
            "bleeding_hollow",
            "blood_furnace",
            "bloodhoof",
            "bloodscalp",
            "bonechewer",
            "borean_tundra",
            "boulderfist",
            "bronzebeard",
            "burning_blade",
            "burning_legion",
            "cairne",
            "cenarion_circle",
            "cenarius",
            "cho_gall",
            "chromaggus",
            "coilfang",
            "crushridge",
            "daggerspine",
            "dalaran",
            "dalvengyr",
            "dark_iron",
            "darkspear",
            "darrowmere",
            "dawnbringer",
            "deathwing",
            "demon_soul",
            "dentarg",
            "destromath",
            "dethecus",
            "detheroc",
            "doomhammer",
            "draenor",
            "dragonblight",
            "dragonmaw",
            "drak_tharon",
            "drak_thul",
            "draka",
            "drenden",
            "dunemaul",
            "durotan",
            "duskwood",
            "earthen_ring",
            "echo_isles",
            "eitrigg",
            "eldre_thalas",
            "elune",
            "emerald_dream",
            "eonar",
            "eredar",
            "executus",
            "exodar", 
            "farstriders",
            "feathermoon",
            "fenris",
            "firetree",
            "fizzcrank",
            "frostmane",
            "frostwolf",
            "galakrond",
            "garithos",
            "garona",
            "garrosh",
            "ghostlands",
            "gilneas",
            "gnomeregan",
            "gorefiend",
            "gorgonnash",
            "greymane",
            "grizzly_hills",
            "gul_dan",
            "gurubashi",
            "hakkar",
            "haomarush",
            "hellscream",
            "hydraxis",
            "hyjal",
            "icecrown",
            "illidan",
            "jaedenar",
            "kael_thas",
            "kalecgos",
            "kargath",
            "kel_thuzad"
            "khadgar",
            "khadgar",
            "khaz_modan",
            "kil_jaeden",
            "kilrogg",
            "korgath",
            "korialstrasz",
            "kul_tiras",
            "laughing_skull",
            "lethon",
            "lightbringer",
            "lightninmaelstrom",
            "lightnings_blade",
            "lightninghoof",
            "llane",
            "lothar",
            "madoran",
            "maelstrom",
            "magtheridon",
            "maiev",
            "mal_ganis",
            "malfurion",
            "malorne",
            "malygos",
            "mannoroth",
            "medivh",
            "misha",
            "mok_nathal",
            "moon_guard",
            "moonrunner",
            "mug_thol",
            "muradin",
            "nathrezim",
            "nazgrel",
            "nazjatar",
            "ner_zhul",
            "nesingwary",
            "nordrassil",
            "norgannon",
            "onyxia",
            "perenolde",
            "proudmoore",
            "quel_thalas",
            "quel_dorei",
            "ragnaros",
            "ravencrest",
            "ravenholdt",
            "rexxar",
            "rivendare",
            "runetotem",
            "sargeras",
            "saurfang",
            "scarlet_crusade",
            "scolla",
            "sen_jin",
            "sentinels",
            "shadow_council",
            "shadowmoon",
            "shadowsong",
            "shandris",
            "shattered_halls", 
            "shattered_hand",
            "shu_halo",
            "silver_hand",
            "silvemoon",
            "sister_of_elune",
            "skullcrusher",
            "skywall",
            "smolderthorn",
            "spinebreaker",
            "spirestone",
            "staghelm",
            "steamwheedle_cartel",
            "stonemaul",
            "stormrage",
            "stormreaver",
            "stormscale",
            "suramar",
            "tanaris",
            "terokkar",
            "thaurissan", 
            "the_forgotten_coast",
            "the_scryers",
            "the_underbog",
            "the_venture_co",
            "thorium_brotherhood",
            "thrall",
            "thunderhorn",
            "thunderlord",
            "tichondrius",
            "tol_barad",
            "tortheldrin",
            "trollbane",
            "turalyon",
            "twisting_nether",
            "uldaman", 
            "uldum",
            "undermine",
            "ursin",
            "uther",
            "vashj",
            "vek_nilash",
            "velen",
            "warsong",
            "whisperwind",
            "wildhammer",
            "windrunner",
            "winterhoof",
            "wyrmrest_accord",
            "ysera",
            "ysondre",
            "zangarmarsh",
            "zul_jin",
            "zuluhead"
        ]

create_tables = """
        ( id int NOT NULL AUTO_INCREMENT,
        item_id int NOT NULL,
        name VARCHAR(100) NOT NULL,
        subclass_name VARCHAR(100) NOT NULL,
        subclass_id int NOT NULL,
        quality_type VARCHAR(100) NOT NULL,
        quality_name VARCHAR(100) NOT NULL,
        level int NOT NULL,
        required_level int NOT NULL,
        item_class_name VARCHAR(100) NOT NULL,
        item_class_id int NOT NULL,
        inventory_type_name VARCHAR(100) NOT NULL,
        inventory_type VARCHAR(100) NOT NULL,
        purchase_price int NOT NULL,
        sell_price int NOT NULL,
        max_count int NOT NULL,
        is_equippable BOOLEAN NOT NULL,
        is_stackable BOOLEAN NOT NULL,
        auction_id int NOT NULL,
        buyout int NOT NULL,
        quantity int NOT NULL,
        unit_price int,
        time_left VARCHAR(100) NOT NULL,
        PRIMARY KEY (id));
"""



def create_table():
    db = mysql_get_mydb()
    cursor = db.cursor()

    with cursor:
        for v in realms:
            table = "create table " + str(v) + create_tables

            print(table)

            cursor.execute(table)
            db.commit()
